export interface ScriptureRef {
  ref: string;
  testament: "OT" | "NT";
}

export interface BibleTheme {
  slug: string;
  name: string;
  description: string;
  category: string;
  categorySlug: string;
  references: ScriptureRef[];
}

export const CATEGORIES = [
  { slug: "god-nature", label: "God & His Nature", color: "bg-violet-100 text-violet-800 border-violet-200" },
  { slug: "salvation-grace", label: "Salvation & Grace", color: "bg-amber-100 text-amber-800 border-amber-200" },
  { slug: "faith-prayer", label: "Faith & Prayer", color: "bg-sky-100 text-sky-800 border-sky-200" },
  { slug: "heart-emotions", label: "Heart & Emotions", color: "bg-rose-100 text-rose-800 border-rose-200" },
  { slug: "character-virtue", label: "Character & Virtue", color: "bg-emerald-100 text-emerald-800 border-emerald-200" },
  { slug: "relationships", label: "Relationships", color: "bg-pink-100 text-pink-800 border-pink-200" },
  { slug: "purpose-identity", label: "Purpose & Identity", color: "bg-indigo-100 text-indigo-800 border-indigo-200" },
  { slug: "life-trials", label: "Life & Trials", color: "bg-orange-100 text-orange-800 border-orange-200" },
  { slug: "church-community", label: "Church & Community", color: "bg-teal-100 text-teal-800 border-teal-200" },
  { slug: "society-ethics", label: "Society & Ethics", color: "bg-lime-100 text-lime-800 border-lime-200" },
] as const;

export const BIBLE_THEMES: BibleTheme[] = [
  // ── God & His Nature ──────────────────────────────────────────────────────
  {
    slug: "gods-love",
    name: "God's Love",
    description: "The boundless, unconditional love God has for humanity — the foundation of all He does.",
    category: "God & His Nature",
    categorySlug: "god-nature",
    references: [
      { ref: "John 3:16", testament: "NT" },
      { ref: "1 John 4:8", testament: "NT" },
      { ref: "Romans 5:8", testament: "NT" },
      { ref: "Psalm 136:1", testament: "OT" },
      { ref: "Jeremiah 31:3", testament: "OT" },
      { ref: "Psalm 86:15", testament: "OT" },
      { ref: "Ephesians 2:4–5", testament: "NT" },
      { ref: "Zephaniah 3:17", testament: "OT" },
      { ref: "Romans 8:38–39", testament: "NT" },
      { ref: "1 John 4:16", testament: "NT" },
    ],
  },
  {
    slug: "gods-power",
    name: "God's Power",
    description: "The omnipotence of God — nothing is too hard for Him, and His strength never fails.",
    category: "God & His Nature",
    categorySlug: "god-nature",
    references: [
      { ref: "Jeremiah 32:17", testament: "OT" },
      { ref: "Matthew 19:26", testament: "NT" },
      { ref: "Psalm 62:11", testament: "OT" },
      { ref: "Isaiah 40:28–31", testament: "OT" },
      { ref: "Revelation 19:6", testament: "NT" },
      { ref: "Job 42:2", testament: "OT" },
      { ref: "Ephesians 3:20", testament: "NT" },
      { ref: "Psalm 147:5", testament: "OT" },
      { ref: "Nahum 1:3", testament: "OT" },
      { ref: "Psalm 29:4", testament: "OT" },
    ],
  },
  {
    slug: "gods-faithfulness",
    name: "God's Faithfulness",
    description: "God's unwavering commitment to His promises — His mercies are new every morning.",
    category: "God & His Nature",
    categorySlug: "god-nature",
    references: [
      { ref: "Lamentations 3:22–23", testament: "OT" },
      { ref: "Psalm 89:8", testament: "OT" },
      { ref: "Deuteronomy 7:9", testament: "OT" },
      { ref: "1 Corinthians 1:9", testament: "NT" },
      { ref: "2 Timothy 2:13", testament: "NT" },
      { ref: "Psalm 36:5", testament: "OT" },
      { ref: "Joshua 21:45", testament: "OT" },
      { ref: "2 Thessalonians 3:3", testament: "NT" },
      { ref: "Hebrews 10:23", testament: "NT" },
      { ref: "Numbers 23:19", testament: "OT" },
    ],
  },
  {
    slug: "gods-sovereignty",
    name: "God's Sovereignty",
    description: "God reigns over all creation — His purposes stand, and He works all things for His glory.",
    category: "God & His Nature",
    categorySlug: "god-nature",
    references: [
      { ref: "Romans 8:28", testament: "NT" },
      { ref: "Daniel 4:34–35", testament: "OT" },
      { ref: "Psalm 115:3", testament: "OT" },
      { ref: "Proverbs 21:1", testament: "OT" },
      { ref: "Isaiah 46:10", testament: "OT" },
      { ref: "Psalm 135:6", testament: "OT" },
      { ref: "Acts 17:26", testament: "NT" },
      { ref: "Revelation 4:11", testament: "NT" },
      { ref: "Isaiah 45:9", testament: "OT" },
      { ref: "Ephesians 1:11", testament: "NT" },
    ],
  },
  {
    slug: "gods-holiness",
    name: "God's Holiness",
    description: "God is utterly set apart, perfectly pure — there is none holy like the Lord.",
    category: "God & His Nature",
    categorySlug: "god-nature",
    references: [
      { ref: "Isaiah 6:3", testament: "OT" },
      { ref: "Revelation 4:8", testament: "NT" },
      { ref: "1 Peter 1:15–16", testament: "NT" },
      { ref: "Psalm 99:9", testament: "OT" },
      { ref: "Exodus 15:11", testament: "OT" },
      { ref: "Leviticus 11:44", testament: "OT" },
      { ref: "Isaiah 57:15", testament: "OT" },
      { ref: "Habakkuk 1:13", testament: "OT" },
      { ref: "Psalm 22:3", testament: "OT" },
      { ref: "1 Samuel 2:2", testament: "OT" },
    ],
  },
  {
    slug: "gods-mercy",
    name: "God's Mercy",
    description: "God's tender compassion — He is slow to anger and abounding in steadfast love.",
    category: "God & His Nature",
    categorySlug: "god-nature",
    references: [
      { ref: "Psalm 103:8–12", testament: "OT" },
      { ref: "Lamentations 3:22", testament: "OT" },
      { ref: "Titus 3:5", testament: "NT" },
      { ref: "Ephesians 2:4", testament: "NT" },
      { ref: "Hebrews 4:16", testament: "NT" },
      { ref: "Numbers 14:18", testament: "OT" },
      { ref: "Micah 7:18", testament: "OT" },
      { ref: "Luke 1:50", testament: "NT" },
      { ref: "Psalm 145:8", testament: "OT" },
      { ref: "Exodus 34:6", testament: "OT" },
    ],
  },
  {
    slug: "the-trinity",
    name: "The Trinity",
    description: "One God in three persons — Father, Son, and Holy Spirit — revealed throughout Scripture.",
    category: "God & His Nature",
    categorySlug: "god-nature",
    references: [
      { ref: "Matthew 28:19", testament: "NT" },
      { ref: "2 Corinthians 13:14", testament: "NT" },
      { ref: "John 10:30", testament: "NT" },
      { ref: "Matthew 3:16–17", testament: "NT" },
      { ref: "Ephesians 4:4–6", testament: "NT" },
      { ref: "John 14:26", testament: "NT" },
      { ref: "Genesis 1:26", testament: "OT" },
      { ref: "John 1:1", testament: "NT" },
      { ref: "Isaiah 48:16", testament: "OT" },
    ],
  },
  {
    slug: "covenant",
    name: "Covenant",
    description: "God's binding promises with His people — from Noah to Abraham to the new covenant in Christ.",
    category: "God & His Nature",
    categorySlug: "god-nature",
    references: [
      { ref: "Genesis 9:8–17", testament: "OT" },
      { ref: "Genesis 15:18", testament: "OT" },
      { ref: "Exodus 24:7–8", testament: "OT" },
      { ref: "Deuteronomy 7:9", testament: "OT" },
      { ref: "Jeremiah 31:31–34", testament: "OT" },
      { ref: "Hebrews 8:6", testament: "NT" },
      { ref: "Hebrews 12:24", testament: "NT" },
      { ref: "Isaiah 54:10", testament: "OT" },
      { ref: "2 Corinthians 3:6", testament: "NT" },
      { ref: "Luke 22:20", testament: "NT" },
    ],
  },
  {
    slug: "gods-provision",
    name: "God's Provision",
    description: "God supplies every need — He is Jehovah Jireh, the Lord who provides.",
    category: "God & His Nature",
    categorySlug: "god-nature",
    references: [
      { ref: "Philippians 4:19", testament: "NT" },
      { ref: "Matthew 6:25–33", testament: "NT" },
      { ref: "Psalm 23:1", testament: "OT" },
      { ref: "Genesis 22:14", testament: "OT" },
      { ref: "Luke 12:24", testament: "NT" },
      { ref: "Psalm 34:9–10", testament: "OT" },
      { ref: "Matthew 7:11", testament: "NT" },
      { ref: "Proverbs 3:9–10", testament: "OT" },
      { ref: "Psalm 37:25", testament: "OT" },
      { ref: "2 Corinthians 9:8", testament: "NT" },
    ],
  },
  {
    slug: "gods-word",
    name: "God's Word & The Bible",
    description: "Scripture is God-breathed — a lamp to our feet and the living, active word that does not return void.",
    category: "God & His Nature",
    categorySlug: "god-nature",
    references: [
      { ref: "2 Timothy 3:16–17", testament: "NT" },
      { ref: "Psalm 119:105", testament: "OT" },
      { ref: "Hebrews 4:12", testament: "NT" },
      { ref: "Joshua 1:8", testament: "OT" },
      { ref: "Isaiah 40:8", testament: "OT" },
      { ref: "Matthew 4:4", testament: "NT" },
      { ref: "Proverbs 30:5", testament: "OT" },
      { ref: "John 17:17", testament: "NT" },
      { ref: "Psalm 19:7–11", testament: "OT" },
      { ref: "Romans 15:4", testament: "NT" },
    ],
  },

  // ── Salvation & Grace ─────────────────────────────────────────────────────
  {
    slug: "salvation",
    name: "Salvation",
    description: "God's rescue of humanity from sin and death — received by faith through Christ alone.",
    category: "Salvation & Grace",
    categorySlug: "salvation-grace",
    references: [
      { ref: "John 3:16–17", testament: "NT" },
      { ref: "Romans 10:9–10", testament: "NT" },
      { ref: "Ephesians 2:8–9", testament: "NT" },
      { ref: "Acts 4:12", testament: "NT" },
      { ref: "John 14:6", testament: "NT" },
      { ref: "1 John 5:11–13", testament: "NT" },
      { ref: "Acts 2:21", testament: "NT" },
      { ref: "Romans 6:23", testament: "NT" },
      { ref: "Titus 3:5", testament: "NT" },
      { ref: "John 1:12", testament: "NT" },
    ],
  },
  {
    slug: "grace",
    name: "Grace",
    description: "God's unmerited favor — His power made perfect in weakness, freely given to all who believe.",
    category: "Salvation & Grace",
    categorySlug: "salvation-grace",
    references: [
      { ref: "Ephesians 2:8–9", testament: "NT" },
      { ref: "2 Corinthians 12:9", testament: "NT" },
      { ref: "John 1:17", testament: "NT" },
      { ref: "Romans 5:20", testament: "NT" },
      { ref: "Titus 2:11–12", testament: "NT" },
      { ref: "Hebrews 4:16", testament: "NT" },
      { ref: "Romans 3:23–24", testament: "NT" },
      { ref: "1 Peter 4:10", testament: "NT" },
      { ref: "2 Timothy 1:9", testament: "NT" },
      { ref: "Zechariah 4:7", testament: "OT" },
    ],
  },
  {
    slug: "forgiveness-from-god",
    name: "Forgiveness from God",
    description: "God casts our sins as far as east is from west — He is faithful and just to forgive.",
    category: "Salvation & Grace",
    categorySlug: "salvation-grace",
    references: [
      { ref: "1 John 1:9", testament: "NT" },
      { ref: "Psalm 103:12", testament: "OT" },
      { ref: "Micah 7:19", testament: "OT" },
      { ref: "Isaiah 43:25", testament: "OT" },
      { ref: "Ephesians 1:7", testament: "NT" },
      { ref: "Colossians 1:14", testament: "NT" },
      { ref: "Acts 3:19", testament: "NT" },
      { ref: "Psalm 32:1–5", testament: "OT" },
      { ref: "Luke 15:11–32", testament: "NT" },
      { ref: "Isaiah 44:22", testament: "OT" },
    ],
  },
  {
    slug: "redemption",
    name: "Redemption",
    description: "Bought back at a great price — Christ's blood secures our freedom from sin's bondage.",
    category: "Salvation & Grace",
    categorySlug: "salvation-grace",
    references: [
      { ref: "Ephesians 1:7", testament: "NT" },
      { ref: "1 Peter 1:18–19", testament: "NT" },
      { ref: "Titus 2:14", testament: "NT" },
      { ref: "Colossians 1:13–14", testament: "NT" },
      { ref: "Galatians 3:13", testament: "NT" },
      { ref: "Revelation 5:9", testament: "NT" },
      { ref: "Isaiah 44:22", testament: "OT" },
      { ref: "Psalm 130:7–8", testament: "OT" },
      { ref: "Romans 3:24", testament: "NT" },
      { ref: "Exodus 15:13", testament: "OT" },
    ],
  },
  {
    slug: "atonement",
    name: "Atonement",
    description: "The sacrifice that covers sin and restores the relationship between God and humanity.",
    category: "Salvation & Grace",
    categorySlug: "salvation-grace",
    references: [
      { ref: "Leviticus 17:11", testament: "OT" },
      { ref: "Hebrews 9:22", testament: "NT" },
      { ref: "1 John 2:2", testament: "NT" },
      { ref: "Romans 5:11", testament: "NT" },
      { ref: "Hebrews 10:10–14", testament: "NT" },
      { ref: "2 Corinthians 5:21", testament: "NT" },
      { ref: "Isaiah 53:4–6", testament: "OT" },
      { ref: "1 Peter 3:18", testament: "NT" },
      { ref: "Hebrews 2:17", testament: "NT" },
      { ref: "Colossians 1:20", testament: "NT" },
    ],
  },
  {
    slug: "eternal-life",
    name: "Eternal Life",
    description: "The gift of life that never ends — knowing God through Jesus Christ, now and forever.",
    category: "Salvation & Grace",
    categorySlug: "salvation-grace",
    references: [
      { ref: "John 3:16", testament: "NT" },
      { ref: "John 10:28", testament: "NT" },
      { ref: "Romans 6:23", testament: "NT" },
      { ref: "1 John 5:13", testament: "NT" },
      { ref: "John 11:25–26", testament: "NT" },
      { ref: "1 Timothy 6:12", testament: "NT" },
      { ref: "Matthew 25:46", testament: "NT" },
      { ref: "John 17:3", testament: "NT" },
      { ref: "Daniel 12:2", testament: "OT" },
      { ref: "2 Timothy 1:10", testament: "NT" },
    ],
  },
  {
    slug: "repentance",
    name: "Repentance",
    description: "Turning from sin toward God — a change of heart and mind that leads to life.",
    category: "Salvation & Grace",
    categorySlug: "salvation-grace",
    references: [
      { ref: "Acts 3:19", testament: "NT" },
      { ref: "Luke 13:3", testament: "NT" },
      { ref: "2 Corinthians 7:10", testament: "NT" },
      { ref: "Ezekiel 18:30–31", testament: "OT" },
      { ref: "Acts 17:30", testament: "NT" },
      { ref: "Mark 1:15", testament: "NT" },
      { ref: "Psalm 51:1–17", testament: "OT" },
      { ref: "Revelation 3:19", testament: "NT" },
      { ref: "Proverbs 28:13", testament: "OT" },
      { ref: "Isaiah 55:7", testament: "OT" },
    ],
  },
  {
    slug: "baptism",
    name: "Baptism",
    description: "An outward act of inward faith — buried with Christ and raised to walk in new life.",
    category: "Salvation & Grace",
    categorySlug: "salvation-grace",
    references: [
      { ref: "Matthew 28:19", testament: "NT" },
      { ref: "Acts 2:38", testament: "NT" },
      { ref: "Romans 6:3–4", testament: "NT" },
      { ref: "Galatians 3:27", testament: "NT" },
      { ref: "Mark 16:16", testament: "NT" },
      { ref: "1 Peter 3:21", testament: "NT" },
      { ref: "Colossians 2:12", testament: "NT" },
      { ref: "Acts 8:36–38", testament: "NT" },
      { ref: "John 3:5–8", testament: "NT" },
      { ref: "Acts 22:16", testament: "NT" },
    ],
  },

  // ── Faith & Prayer ────────────────────────────────────────────────────────
  {
    slug: "faith",
    name: "Faith",
    description: "The assurance of things hoped for — trusting God's promises even when unseen.",
    category: "Faith & Prayer",
    categorySlug: "faith-prayer",
    references: [
      { ref: "Hebrews 11:1", testament: "NT" },
      { ref: "Hebrews 11:6", testament: "NT" },
      { ref: "Romans 10:17", testament: "NT" },
      { ref: "James 2:17", testament: "NT" },
      { ref: "Ephesians 2:8–9", testament: "NT" },
      { ref: "2 Corinthians 5:7", testament: "NT" },
      { ref: "Mark 11:22", testament: "NT" },
      { ref: "Matthew 17:20", testament: "NT" },
      { ref: "Galatians 2:20", testament: "NT" },
      { ref: "Romans 1:17", testament: "NT" },
    ],
  },
  {
    slug: "trust-in-god",
    name: "Trust in God",
    description: "Leaning not on our own understanding — surrendering control to the One who holds all things.",
    category: "Faith & Prayer",
    categorySlug: "faith-prayer",
    references: [
      { ref: "Proverbs 3:5–6", testament: "OT" },
      { ref: "Psalm 37:3–5", testament: "OT" },
      { ref: "Psalm 62:8", testament: "OT" },
      { ref: "Isaiah 26:4", testament: "OT" },
      { ref: "Jeremiah 17:7–8", testament: "OT" },
      { ref: "Psalm 56:3–4", testament: "OT" },
      { ref: "Psalm 118:8", testament: "OT" },
      { ref: "Nahum 1:7", testament: "OT" },
      { ref: "Psalm 9:10", testament: "OT" },
      { ref: "Isaiah 12:2", testament: "OT" },
    ],
  },
  {
    slug: "prayer",
    name: "Prayer",
    description: "Communicating with God — bringing every request, praise, and concern to the Father.",
    category: "Faith & Prayer",
    categorySlug: "faith-prayer",
    references: [
      { ref: "Matthew 6:9–13", testament: "NT" },
      { ref: "Philippians 4:6", testament: "NT" },
      { ref: "1 Thessalonians 5:17", testament: "NT" },
      { ref: "Luke 18:1–8", testament: "NT" },
      { ref: "Jeremiah 29:12", testament: "OT" },
      { ref: "Psalm 145:18", testament: "OT" },
      { ref: "James 5:16", testament: "NT" },
      { ref: "Mark 11:24", testament: "NT" },
      { ref: "John 15:7", testament: "NT" },
      { ref: "Luke 11:9–10", testament: "NT" },
    ],
  },
  {
    slug: "praise-worship",
    name: "Praise & Worship",
    description: "Exalting God with all we have — true worshipers worship in spirit and in truth.",
    category: "Faith & Prayer",
    categorySlug: "faith-prayer",
    references: [
      { ref: "Psalm 100:1–5", testament: "OT" },
      { ref: "Psalm 150:1–6", testament: "OT" },
      { ref: "John 4:24", testament: "NT" },
      { ref: "Hebrews 13:15", testament: "NT" },
      { ref: "Ephesians 5:19", testament: "NT" },
      { ref: "Colossians 3:16", testament: "NT" },
      { ref: "Psalm 95:1–6", testament: "OT" },
      { ref: "Revelation 4:11", testament: "NT" },
      { ref: "Psalm 22:3", testament: "OT" },
      { ref: "Psalm 34:1", testament: "OT" },
    ],
  },
  {
    slug: "fasting",
    name: "Fasting",
    description: "Denying the body to seek God — a spiritual discipline that sharpens hunger for the Lord.",
    category: "Faith & Prayer",
    categorySlug: "faith-prayer",
    references: [
      { ref: "Matthew 6:16–18", testament: "NT" },
      { ref: "Isaiah 58:6–7", testament: "OT" },
      { ref: "Joel 2:12", testament: "OT" },
      { ref: "Acts 14:23", testament: "NT" },
      { ref: "Matthew 4:2", testament: "NT" },
      { ref: "2 Samuel 12:16", testament: "OT" },
      { ref: "Daniel 9:3", testament: "OT" },
      { ref: "Luke 2:37", testament: "NT" },
      { ref: "Ezra 8:21–23", testament: "OT" },
      { ref: "Nehemiah 1:4", testament: "OT" },
    ],
  },
  {
    slug: "thanksgiving",
    name: "Thanksgiving",
    description: "Giving thanks in all circumstances — a heart of gratitude pleases God and strengthens faith.",
    category: "Faith & Prayer",
    categorySlug: "faith-prayer",
    references: [
      { ref: "1 Thessalonians 5:18", testament: "NT" },
      { ref: "Colossians 3:17", testament: "NT" },
      { ref: "Psalm 107:1", testament: "OT" },
      { ref: "Philippians 4:6", testament: "NT" },
      { ref: "Psalm 100:4", testament: "OT" },
      { ref: "Ephesians 5:20", testament: "NT" },
      { ref: "Psalm 103:1–5", testament: "OT" },
      { ref: "Luke 17:11–19", testament: "NT" },
      { ref: "1 Chronicles 16:34", testament: "OT" },
      { ref: "Psalm 9:1", testament: "OT" },
    ],
  },
  {
    slug: "doubt",
    name: "Doubt",
    description: "Wrestling with uncertainty — honest doubt met by God's patient, sustaining truth.",
    category: "Faith & Prayer",
    categorySlug: "faith-prayer",
    references: [
      { ref: "Matthew 14:31", testament: "NT" },
      { ref: "Mark 9:24", testament: "NT" },
      { ref: "John 20:27–29", testament: "NT" },
      { ref: "James 1:6", testament: "NT" },
      { ref: "Jude 1:22", testament: "NT" },
      { ref: "Psalm 73:13–17", testament: "OT" },
      { ref: "Isaiah 40:27–28", testament: "OT" },
      { ref: "Matthew 21:21", testament: "NT" },
      { ref: "Job 23:3–9", testament: "OT" },
      { ref: "Psalm 22:1–2", testament: "OT" },
    ],
  },
  {
    slug: "obedience",
    name: "Obedience",
    description: "Loving God means keeping His commandments — obedience is better than sacrifice.",
    category: "Faith & Prayer",
    categorySlug: "faith-prayer",
    references: [
      { ref: "John 14:15", testament: "NT" },
      { ref: "1 Samuel 15:22", testament: "OT" },
      { ref: "Deuteronomy 28:1–2", testament: "OT" },
      { ref: "John 15:10", testament: "NT" },
      { ref: "Luke 6:46", testament: "NT" },
      { ref: "Romans 6:16", testament: "NT" },
      { ref: "1 John 5:3", testament: "NT" },
      { ref: "Acts 5:29", testament: "NT" },
      { ref: "Hebrews 5:8", testament: "NT" },
      { ref: "Matthew 7:24–27", testament: "NT" },
    ],
  },

  // ── Heart & Emotions ──────────────────────────────────────────────────────
  {
    slug: "fear-anxiety",
    name: "Fear & Anxiety",
    description: "God speaks 'do not fear' throughout Scripture — cast every anxiety on Him, for He cares.",
    category: "Heart & Emotions",
    categorySlug: "heart-emotions",
    references: [
      { ref: "Psalm 23:4", testament: "OT" },
      { ref: "Isaiah 41:10", testament: "OT" },
      { ref: "Philippians 4:6–7", testament: "NT" },
      { ref: "2 Timothy 1:7", testament: "NT" },
      { ref: "Matthew 6:25–27", testament: "NT" },
      { ref: "1 Peter 5:7", testament: "NT" },
      { ref: "Psalm 27:1", testament: "OT" },
      { ref: "John 14:27", testament: "NT" },
      { ref: "Psalm 34:4", testament: "OT" },
      { ref: "Joshua 1:9", testament: "OT" },
    ],
  },
  {
    slug: "peace",
    name: "Peace",
    description: "The peace of God that surpasses understanding — shalom that the world cannot give.",
    category: "Heart & Emotions",
    categorySlug: "heart-emotions",
    references: [
      { ref: "John 14:27", testament: "NT" },
      { ref: "Philippians 4:7", testament: "NT" },
      { ref: "Isaiah 26:3", testament: "OT" },
      { ref: "Colossians 3:15", testament: "NT" },
      { ref: "Psalm 29:11", testament: "OT" },
      { ref: "Numbers 6:26", testament: "OT" },
      { ref: "Romans 5:1", testament: "NT" },
      { ref: "Matthew 5:9", testament: "NT" },
      { ref: "John 16:33", testament: "NT" },
      { ref: "Psalm 119:165", testament: "OT" },
    ],
  },
  {
    slug: "joy",
    name: "Joy",
    description: "The joy of the Lord is our strength — a deep gladness rooted not in circumstance but in God.",
    category: "Heart & Emotions",
    categorySlug: "heart-emotions",
    references: [
      { ref: "Nehemiah 8:10", testament: "OT" },
      { ref: "Psalm 16:11", testament: "OT" },
      { ref: "Galatians 5:22", testament: "NT" },
      { ref: "Philippians 4:4", testament: "NT" },
      { ref: "James 1:2–3", testament: "NT" },
      { ref: "Psalm 30:5", testament: "OT" },
      { ref: "Isaiah 61:3", testament: "OT" },
      { ref: "John 15:11", testament: "NT" },
      { ref: "Psalm 126:5–6", testament: "OT" },
      { ref: "Romans 15:13", testament: "NT" },
    ],
  },
  {
    slug: "grief-mourning",
    name: "Grief & Mourning",
    description: "God is close to the brokenhearted — He sees our tears and turns mourning into dancing.",
    category: "Heart & Emotions",
    categorySlug: "heart-emotions",
    references: [
      { ref: "Matthew 5:4", testament: "NT" },
      { ref: "Psalm 34:18", testament: "OT" },
      { ref: "Psalm 147:3", testament: "OT" },
      { ref: "Revelation 21:4", testament: "NT" },
      { ref: "Isaiah 61:1–3", testament: "OT" },
      { ref: "John 11:35", testament: "NT" },
      { ref: "2 Corinthians 1:3–4", testament: "NT" },
      { ref: "Psalm 30:5", testament: "OT" },
      { ref: "Lamentations 3:32–33", testament: "OT" },
      { ref: "Psalm 56:8", testament: "OT" },
    ],
  },
  {
    slug: "anger",
    name: "Anger",
    description: "Be angry and do not sin — Scripture teaches how to handle wrath before it takes root.",
    category: "Heart & Emotions",
    categorySlug: "heart-emotions",
    references: [
      { ref: "Ephesians 4:26–27", testament: "NT" },
      { ref: "Proverbs 15:1", testament: "OT" },
      { ref: "James 1:19–20", testament: "NT" },
      { ref: "Psalm 4:4", testament: "OT" },
      { ref: "Proverbs 14:29", testament: "OT" },
      { ref: "Proverbs 29:11", testament: "OT" },
      { ref: "Colossians 3:8", testament: "NT" },
      { ref: "Proverbs 16:32", testament: "OT" },
      { ref: "Psalm 37:8", testament: "OT" },
      { ref: "Ecclesiastes 7:9", testament: "OT" },
    ],
  },
  {
    slug: "loneliness",
    name: "Loneliness",
    description: "God sets the lonely in families — He promises never to leave or forsake His own.",
    category: "Heart & Emotions",
    categorySlug: "heart-emotions",
    references: [
      { ref: "Psalm 68:6", testament: "OT" },
      { ref: "Hebrews 13:5", testament: "NT" },
      { ref: "Matthew 28:20", testament: "NT" },
      { ref: "John 14:18", testament: "NT" },
      { ref: "Isaiah 41:10", testament: "OT" },
      { ref: "Genesis 2:18", testament: "OT" },
      { ref: "Psalm 139:1–18", testament: "OT" },
      { ref: "Psalm 25:16", testament: "OT" },
      { ref: "Deuteronomy 31:8", testament: "OT" },
      { ref: "2 Timothy 4:17", testament: "NT" },
    ],
  },
  {
    slug: "depression-despair",
    name: "Depression & Despair",
    description: "Even in the darkest valley, God's presence sustains — He lifts the head and restores the soul.",
    category: "Heart & Emotions",
    categorySlug: "heart-emotions",
    references: [
      { ref: "Psalm 42:5–6", testament: "OT" },
      { ref: "Psalm 34:18", testament: "OT" },
      { ref: "Isaiah 41:10", testament: "OT" },
      { ref: "1 Kings 19:1–18", testament: "OT" },
      { ref: "Psalm 30:2–3", testament: "OT" },
      { ref: "Matthew 11:28–29", testament: "NT" },
      { ref: "Romans 8:28", testament: "NT" },
      { ref: "Psalm 43:5", testament: "OT" },
      { ref: "Psalm 88:1–18", testament: "OT" },
      { ref: "2 Corinthians 4:8–9", testament: "NT" },
    ],
  },
  {
    slug: "hope",
    name: "Hope",
    description: "An anchor for the soul — hope rooted in God's promises does not disappoint.",
    category: "Heart & Emotions",
    categorySlug: "heart-emotions",
    references: [
      { ref: "Romans 15:13", testament: "NT" },
      { ref: "Jeremiah 29:11", testament: "OT" },
      { ref: "Hebrews 6:19", testament: "NT" },
      { ref: "Psalm 31:24", testament: "OT" },
      { ref: "Romans 8:28", testament: "NT" },
      { ref: "Lamentations 3:22–23", testament: "OT" },
      { ref: "1 Peter 1:3", testament: "NT" },
      { ref: "Psalm 33:18", testament: "OT" },
      { ref: "Isaiah 40:31", testament: "OT" },
      { ref: "Romans 5:2–5", testament: "NT" },
    ],
  },
  {
    slug: "contentment",
    name: "Contentment",
    description: "Learning in every state to be content — godliness with contentment is great gain.",
    category: "Heart & Emotions",
    categorySlug: "heart-emotions",
    references: [
      { ref: "Philippians 4:11–13", testament: "NT" },
      { ref: "1 Timothy 6:6–8", testament: "NT" },
      { ref: "Hebrews 13:5", testament: "NT" },
      { ref: "Proverbs 19:23", testament: "OT" },
      { ref: "Luke 3:14", testament: "NT" },
      { ref: "Psalm 23:1", testament: "OT" },
      { ref: "Matthew 6:31–33", testament: "NT" },
      { ref: "Ecclesiastes 5:10–12", testament: "OT" },
      { ref: "1 Timothy 6:17", testament: "NT" },
      { ref: "Psalm 131:2", testament: "OT" },
    ],
  },
  {
    slug: "worry",
    name: "Worry",
    description: "Do not be anxious about anything — God invites us to cast every care upon Him.",
    category: "Heart & Emotions",
    categorySlug: "heart-emotions",
    references: [
      { ref: "Matthew 6:25–34", testament: "NT" },
      { ref: "Philippians 4:6–7", testament: "NT" },
      { ref: "1 Peter 5:7", testament: "NT" },
      { ref: "Luke 12:22–31", testament: "NT" },
      { ref: "Psalm 55:22", testament: "OT" },
      { ref: "Proverbs 12:25", testament: "OT" },
      { ref: "Isaiah 35:4", testament: "OT" },
      { ref: "Matthew 6:34", testament: "NT" },
      { ref: "Psalm 94:19", testament: "OT" },
      { ref: "John 14:1", testament: "NT" },
    ],
  },
  {
    slug: "gratitude",
    name: "Gratitude",
    description: "Enter His gates with thanksgiving — a grateful heart acknowledges God in all things.",
    category: "Heart & Emotions",
    categorySlug: "heart-emotions",
    references: [
      { ref: "1 Thessalonians 5:18", testament: "NT" },
      { ref: "Colossians 3:17", testament: "NT" },
      { ref: "Psalm 100:4", testament: "OT" },
      { ref: "Philippians 4:6", testament: "NT" },
      { ref: "Ephesians 5:20", testament: "NT" },
      { ref: "Psalm 107:1", testament: "OT" },
      { ref: "Psalm 9:1", testament: "OT" },
      { ref: "Luke 17:11–19", testament: "NT" },
      { ref: "Psalm 118:24", testament: "OT" },
      { ref: "Colossians 2:7", testament: "NT" },
    ],
  },
  {
    slug: "healing",
    name: "Healing",
    description: "By His stripes we are healed — God is Jehovah Rapha, the Lord who heals body and soul.",
    category: "Heart & Emotions",
    categorySlug: "heart-emotions",
    references: [
      { ref: "Psalm 147:3", testament: "OT" },
      { ref: "James 5:14–16", testament: "NT" },
      { ref: "Isaiah 53:5", testament: "OT" },
      { ref: "Matthew 4:24", testament: "NT" },
      { ref: "Mark 16:18", testament: "NT" },
      { ref: "Jeremiah 17:14", testament: "OT" },
      { ref: "3 John 1:2", testament: "NT" },
      { ref: "Exodus 15:26", testament: "OT" },
      { ref: "Luke 4:18", testament: "NT" },
      { ref: "Acts 10:38", testament: "NT" },
    ],
  },

  // ── Character & Virtue ────────────────────────────────────────────────────
  {
    slug: "humility",
    name: "Humility",
    description: "God opposes the proud but gives grace to the humble — the path of greatness runs downward.",
    category: "Character & Virtue",
    categorySlug: "character-virtue",
    references: [
      { ref: "Philippians 2:3–4", testament: "NT" },
      { ref: "Proverbs 11:2", testament: "OT" },
      { ref: "James 4:6", testament: "NT" },
      { ref: "1 Peter 5:6", testament: "NT" },
      { ref: "Matthew 23:12", testament: "NT" },
      { ref: "Micah 6:8", testament: "OT" },
      { ref: "Proverbs 22:4", testament: "OT" },
      { ref: "Colossians 3:12", testament: "NT" },
      { ref: "Matthew 18:4", testament: "NT" },
      { ref: "Luke 14:11", testament: "NT" },
    ],
  },
  {
    slug: "integrity",
    name: "Integrity",
    description: "Whoever walks in integrity walks securely — a blameless life before God and others.",
    category: "Character & Virtue",
    categorySlug: "character-virtue",
    references: [
      { ref: "Proverbs 10:9", testament: "OT" },
      { ref: "Psalm 15:1–5", testament: "OT" },
      { ref: "Proverbs 11:3", testament: "OT" },
      { ref: "1 Chronicles 29:17", testament: "OT" },
      { ref: "Titus 2:7–8", testament: "NT" },
      { ref: "Proverbs 20:7", testament: "OT" },
      { ref: "Psalm 25:21", testament: "OT" },
      { ref: "Proverbs 28:6", testament: "OT" },
      { ref: "Job 2:3", testament: "OT" },
      { ref: "Luke 16:10", testament: "NT" },
    ],
  },
  {
    slug: "patience",
    name: "Patience",
    description: "Wait on the Lord — trials produce patience, and patience produces proven character.",
    category: "Character & Virtue",
    categorySlug: "character-virtue",
    references: [
      { ref: "James 1:3–4", testament: "NT" },
      { ref: "Romans 5:3–4", testament: "NT" },
      { ref: "Hebrews 12:1", testament: "NT" },
      { ref: "Psalm 27:14", testament: "OT" },
      { ref: "Proverbs 14:29", testament: "OT" },
      { ref: "Ecclesiastes 7:8", testament: "OT" },
      { ref: "Galatians 6:9", testament: "NT" },
      { ref: "Lamentations 3:25–26", testament: "OT" },
      { ref: "Romans 8:25", testament: "NT" },
      { ref: "2 Peter 3:9", testament: "NT" },
    ],
  },
  {
    slug: "courage",
    name: "Courage",
    description: "Be strong and courageous — God's presence banishes fear and emboldens His servants.",
    category: "Character & Virtue",
    categorySlug: "character-virtue",
    references: [
      { ref: "Joshua 1:9", testament: "OT" },
      { ref: "Deuteronomy 31:6", testament: "OT" },
      { ref: "Psalm 27:14", testament: "OT" },
      { ref: "Isaiah 41:10", testament: "OT" },
      { ref: "2 Timothy 1:7", testament: "NT" },
      { ref: "Acts 4:29–31", testament: "NT" },
      { ref: "Proverbs 28:1", testament: "OT" },
      { ref: "Ephesians 6:19–20", testament: "NT" },
      { ref: "1 Corinthians 16:13", testament: "NT" },
      { ref: "Hebrews 13:6", testament: "NT" },
    ],
  },
  {
    slug: "honesty",
    name: "Honesty & Truth",
    description: "Speak the truth in love — God hates lying lips and delights in those who deal faithfully.",
    category: "Character & Virtue",
    categorySlug: "character-virtue",
    references: [
      { ref: "Proverbs 12:17", testament: "OT" },
      { ref: "Ephesians 4:15", testament: "NT" },
      { ref: "Proverbs 12:22", testament: "OT" },
      { ref: "Zechariah 8:16", testament: "OT" },
      { ref: "Colossians 3:9", testament: "NT" },
      { ref: "John 8:32", testament: "NT" },
      { ref: "Psalm 15:1–2", testament: "OT" },
      { ref: "Proverbs 11:3", testament: "OT" },
      { ref: "Leviticus 19:11", testament: "OT" },
      { ref: "Proverbs 19:5", testament: "OT" },
    ],
  },
  {
    slug: "generosity",
    name: "Generosity",
    description: "Whoever sows bountifully reaps bountifully — a generous spirit reflects God's own heart.",
    category: "Character & Virtue",
    categorySlug: "character-virtue",
    references: [
      { ref: "2 Corinthians 9:6–8", testament: "NT" },
      { ref: "Proverbs 11:24–25", testament: "OT" },
      { ref: "Luke 6:38", testament: "NT" },
      { ref: "1 Timothy 6:17–19", testament: "NT" },
      { ref: "Proverbs 19:17", testament: "OT" },
      { ref: "Matthew 5:42", testament: "NT" },
      { ref: "Acts 20:35", testament: "NT" },
      { ref: "Proverbs 22:9", testament: "OT" },
      { ref: "Deuteronomy 15:10", testament: "OT" },
      { ref: "Luke 21:1–4", testament: "NT" },
    ],
  },
  {
    slug: "kindness",
    name: "Kindness",
    description: "Be kind and tenderhearted — the fruit of the Spirit overflows in how we treat others.",
    category: "Character & Virtue",
    categorySlug: "character-virtue",
    references: [
      { ref: "Ephesians 4:32", testament: "NT" },
      { ref: "Colossians 3:12", testament: "NT" },
      { ref: "Proverbs 19:22", testament: "OT" },
      { ref: "Galatians 5:22", testament: "NT" },
      { ref: "Luke 6:35", testament: "NT" },
      { ref: "Psalm 117:2", testament: "OT" },
      { ref: "Micah 6:8", testament: "OT" },
      { ref: "Romans 2:4", testament: "NT" },
      { ref: "Ruth 2:20", testament: "OT" },
      { ref: "Proverbs 31:26", testament: "OT" },
    ],
  },
  {
    slug: "self-control",
    name: "Self-Control",
    description: "A man without self-control is like a city with broken walls — disciplining the flesh is freedom.",
    category: "Character & Virtue",
    categorySlug: "character-virtue",
    references: [
      { ref: "Galatians 5:22–23", testament: "NT" },
      { ref: "2 Peter 1:5–7", testament: "NT" },
      { ref: "Proverbs 25:28", testament: "OT" },
      { ref: "1 Corinthians 9:27", testament: "NT" },
      { ref: "Titus 2:12", testament: "NT" },
      { ref: "2 Timothy 1:7", testament: "NT" },
      { ref: "Proverbs 16:32", testament: "OT" },
      { ref: "Psalm 119:11", testament: "OT" },
      { ref: "1 Corinthians 6:12", testament: "NT" },
      { ref: "1 Peter 2:11", testament: "NT" },
    ],
  },
  {
    slug: "diligence",
    name: "Diligence",
    description: "Whatever your hand finds to do, do it with all your might — God honors faithful labor.",
    category: "Character & Virtue",
    categorySlug: "character-virtue",
    references: [
      { ref: "Proverbs 6:6–8", testament: "OT" },
      { ref: "Colossians 3:23", testament: "NT" },
      { ref: "Proverbs 12:11", testament: "OT" },
      { ref: "Ecclesiastes 9:10", testament: "OT" },
      { ref: "2 Thessalonians 3:10–12", testament: "NT" },
      { ref: "Proverbs 13:4", testament: "OT" },
      { ref: "Proverbs 22:29", testament: "OT" },
      { ref: "Proverbs 10:4", testament: "OT" },
      { ref: "Romans 12:11", testament: "NT" },
      { ref: "Hebrews 6:11", testament: "NT" },
    ],
  },
  {
    slug: "wisdom",
    name: "Wisdom",
    description: "Fear of the Lord is the beginning of wisdom — ask and God gives it generously.",
    category: "Character & Virtue",
    categorySlug: "character-virtue",
    references: [
      { ref: "Proverbs 1:7", testament: "OT" },
      { ref: "James 1:5", testament: "NT" },
      { ref: "Proverbs 4:6–7", testament: "OT" },
      { ref: "Proverbs 9:10", testament: "OT" },
      { ref: "Psalm 111:10", testament: "OT" },
      { ref: "Ecclesiastes 12:13", testament: "OT" },
      { ref: "1 Kings 3:9", testament: "OT" },
      { ref: "Colossians 2:3", testament: "NT" },
      { ref: "Proverbs 3:13–18", testament: "OT" },
      { ref: "Daniel 2:20", testament: "OT" },
    ],
  },
  {
    slug: "compassion",
    name: "Compassion",
    description: "Clothe yourself with compassion — moved by the needs of others as Christ was moved.",
    category: "Character & Virtue",
    categorySlug: "character-virtue",
    references: [
      { ref: "Matthew 9:36", testament: "NT" },
      { ref: "Luke 10:33–37", testament: "NT" },
      { ref: "Colossians 3:12", testament: "NT" },
      { ref: "1 Peter 3:8", testament: "NT" },
      { ref: "Psalm 145:9", testament: "OT" },
      { ref: "Zechariah 7:9", testament: "OT" },
      { ref: "Matthew 25:34–40", testament: "NT" },
      { ref: "Micah 6:8", testament: "OT" },
      { ref: "2 Corinthians 1:3–4", testament: "NT" },
      { ref: "Isaiah 63:9", testament: "OT" },
    ],
  },
  {
    slug: "love-for-others",
    name: "Love for One Another",
    description: "Love one another as I have loved you — the greatest commandment that fulfills all the Law.",
    category: "Character & Virtue",
    categorySlug: "character-virtue",
    references: [
      { ref: "John 13:34–35", testament: "NT" },
      { ref: "1 John 4:7–11", testament: "NT" },
      { ref: "Matthew 22:39", testament: "NT" },
      { ref: "1 Corinthians 13:1–13", testament: "NT" },
      { ref: "Romans 13:8–10", testament: "NT" },
      { ref: "1 Peter 4:8", testament: "NT" },
      { ref: "Galatians 5:14", testament: "NT" },
      { ref: "John 15:12–13", testament: "NT" },
      { ref: "Matthew 5:44", testament: "NT" },
      { ref: "Ephesians 5:2", testament: "NT" },
    ],
  },

  // ── Relationships ─────────────────────────────────────────────────────────
  {
    slug: "marriage",
    name: "Marriage",
    description: "Two become one flesh — a covenant relationship that reflects Christ's love for the Church.",
    category: "Relationships",
    categorySlug: "relationships",
    references: [
      { ref: "Genesis 2:24", testament: "OT" },
      { ref: "Ephesians 5:22–33", testament: "NT" },
      { ref: "Proverbs 18:22", testament: "OT" },
      { ref: "1 Corinthians 7:1–16", testament: "NT" },
      { ref: "Hebrews 13:4", testament: "NT" },
      { ref: "Colossians 3:18–19", testament: "NT" },
      { ref: "Matthew 19:4–6", testament: "NT" },
      { ref: "Song of Solomon 8:6–7", testament: "OT" },
      { ref: "Proverbs 31:10–31", testament: "OT" },
      { ref: "1 Peter 3:1–7", testament: "NT" },
    ],
  },
  {
    slug: "friendship",
    name: "Friendship",
    description: "A friend loves at all times — Scripture celebrates the beauty of loyal, Christ-centered friendship.",
    category: "Relationships",
    categorySlug: "relationships",
    references: [
      { ref: "Proverbs 17:17", testament: "OT" },
      { ref: "Proverbs 18:24", testament: "OT" },
      { ref: "John 15:13", testament: "NT" },
      { ref: "1 Samuel 18:1–3", testament: "OT" },
      { ref: "Ecclesiastes 4:9–10", testament: "OT" },
      { ref: "Colossians 3:12–14", testament: "NT" },
      { ref: "Ruth 1:16–17", testament: "OT" },
      { ref: "Proverbs 27:9", testament: "OT" },
      { ref: "Psalm 133:1", testament: "OT" },
      { ref: "James 2:23", testament: "NT" },
    ],
  },
  {
    slug: "family",
    name: "Family",
    description: "God places the lonely in families — family is designed to reflect His love across generations.",
    category: "Relationships",
    categorySlug: "relationships",
    references: [
      { ref: "Proverbs 22:6", testament: "OT" },
      { ref: "Ephesians 6:1–4", testament: "NT" },
      { ref: "Colossians 3:20–21", testament: "NT" },
      { ref: "Psalm 128:1–4", testament: "OT" },
      { ref: "Deuteronomy 6:6–7", testament: "OT" },
      { ref: "Psalm 127:3", testament: "OT" },
      { ref: "1 Timothy 5:8", testament: "NT" },
      { ref: "Joshua 24:15", testament: "OT" },
      { ref: "Mark 10:13–16", testament: "NT" },
      { ref: "Genesis 2:24", testament: "OT" },
    ],
  },
  {
    slug: "parenting",
    name: "Parenting",
    description: "Train up a child in the way they should go — parenting is a sacred stewardship before God.",
    category: "Relationships",
    categorySlug: "relationships",
    references: [
      { ref: "Proverbs 22:6", testament: "OT" },
      { ref: "Proverbs 13:24", testament: "OT" },
      { ref: "Deuteronomy 6:6–7", testament: "OT" },
      { ref: "Psalm 127:3–5", testament: "OT" },
      { ref: "Ephesians 6:4", testament: "NT" },
      { ref: "3 John 1:4", testament: "NT" },
      { ref: "Matthew 19:14", testament: "NT" },
      { ref: "Psalm 78:4–6", testament: "OT" },
      { ref: "Proverbs 29:17", testament: "OT" },
      { ref: "Colossians 3:21", testament: "NT" },
    ],
  },
  {
    slug: "forgiveness-toward-others",
    name: "Forgiving Others",
    description: "Forgive as the Lord has forgiven you — releasing others from debt frees the forgiver.",
    category: "Relationships",
    categorySlug: "relationships",
    references: [
      { ref: "Matthew 6:14–15", testament: "NT" },
      { ref: "Colossians 3:13", testament: "NT" },
      { ref: "Ephesians 4:32", testament: "NT" },
      { ref: "Matthew 18:21–22", testament: "NT" },
      { ref: "Luke 17:3–4", testament: "NT" },
      { ref: "Matthew 5:44", testament: "NT" },
      { ref: "Mark 11:25", testament: "NT" },
      { ref: "Luke 23:34", testament: "NT" },
      { ref: "Proverbs 17:9", testament: "OT" },
      { ref: "Romans 12:17–21", testament: "NT" },
    ],
  },
  {
    slug: "singleness",
    name: "Singleness",
    description: "The gift of singleness allows undivided devotion to God — a calling honored in Scripture.",
    category: "Relationships",
    categorySlug: "relationships",
    references: [
      { ref: "1 Corinthians 7:7–9", testament: "NT" },
      { ref: "1 Corinthians 7:32–35", testament: "NT" },
      { ref: "Matthew 19:11–12", testament: "NT" },
      { ref: "Isaiah 54:5", testament: "OT" },
      { ref: "Psalm 68:6", testament: "OT" },
      { ref: "Isaiah 56:3–5", testament: "OT" },
      { ref: "Jeremiah 16:1–2", testament: "OT" },
      { ref: "Matthew 19:12", testament: "NT" },
    ],
  },
  {
    slug: "sexuality-purity",
    name: "Sexuality & Purity",
    description: "Flee sexual immorality — the body is a temple of the Holy Spirit and designed for God's glory.",
    category: "Relationships",
    categorySlug: "relationships",
    references: [
      { ref: "1 Corinthians 6:18–20", testament: "NT" },
      { ref: "Hebrews 13:4", testament: "NT" },
      { ref: "1 Thessalonians 4:3–5", testament: "NT" },
      { ref: "Matthew 5:27–28", testament: "NT" },
      { ref: "Colossians 3:5", testament: "NT" },
      { ref: "1 Corinthians 7:1–7", testament: "NT" },
      { ref: "1 Peter 2:11", testament: "NT" },
      { ref: "Job 31:1", testament: "OT" },
      { ref: "Galatians 5:19–21", testament: "NT" },
      { ref: "Song of Solomon 2:7", testament: "OT" },
    ],
  },
  {
    slug: "reconciliation",
    name: "Reconciliation",
    description: "God reconciled us to Himself through Christ — we are ambassadors of that same reconciliation.",
    category: "Relationships",
    categorySlug: "relationships",
    references: [
      { ref: "Matthew 5:23–24", testament: "NT" },
      { ref: "2 Corinthians 5:18–20", testament: "NT" },
      { ref: "Romans 5:10–11", testament: "NT" },
      { ref: "Ephesians 2:14–16", testament: "NT" },
      { ref: "Colossians 1:20–22", testament: "NT" },
      { ref: "Matthew 18:15–17", testament: "NT" },
      { ref: "Luke 15:11–32", testament: "NT" },
      { ref: "Philemon 1:10–16", testament: "NT" },
    ],
  },

  // ── Purpose & Identity ────────────────────────────────────────────────────
  {
    slug: "identity-in-christ",
    name: "Identity in Christ",
    description: "You are a new creation — your deepest identity is found in who God says you are in Christ.",
    category: "Purpose & Identity",
    categorySlug: "purpose-identity",
    references: [
      { ref: "2 Corinthians 5:17", testament: "NT" },
      { ref: "Galatians 2:20", testament: "NT" },
      { ref: "John 1:12", testament: "NT" },
      { ref: "Romans 8:16–17", testament: "NT" },
      { ref: "Ephesians 1:3–14", testament: "NT" },
      { ref: "Colossians 3:3", testament: "NT" },
      { ref: "1 Peter 2:9–10", testament: "NT" },
      { ref: "1 John 3:1", testament: "NT" },
      { ref: "Romans 8:37", testament: "NT" },
      { ref: "Zephaniah 3:17", testament: "OT" },
    ],
  },
  {
    slug: "purpose-calling",
    name: "Purpose & Calling",
    description: "God's plans are to prosper and not harm — He knew you before you were born and has a purpose for your life.",
    category: "Purpose & Identity",
    categorySlug: "purpose-identity",
    references: [
      { ref: "Jeremiah 29:11", testament: "OT" },
      { ref: "Romans 8:28", testament: "NT" },
      { ref: "Ephesians 2:10", testament: "NT" },
      { ref: "1 Corinthians 12:4–7", testament: "NT" },
      { ref: "Proverbs 19:21", testament: "OT" },
      { ref: "Psalm 139:13–16", testament: "OT" },
      { ref: "Isaiah 43:1", testament: "OT" },
      { ref: "2 Timothy 1:9", testament: "NT" },
      { ref: "Romans 8:30", testament: "NT" },
      { ref: "John 15:16", testament: "NT" },
    ],
  },
  {
    slug: "self-worth",
    name: "Self-Worth & Value",
    description: "You are fearfully and wonderfully made — God declares your worth through creation and redemption.",
    category: "Purpose & Identity",
    categorySlug: "purpose-identity",
    references: [
      { ref: "Psalm 139:13–16", testament: "OT" },
      { ref: "Matthew 10:31", testament: "NT" },
      { ref: "Luke 12:7", testament: "NT" },
      { ref: "1 Peter 2:9", testament: "NT" },
      { ref: "Ephesians 2:10", testament: "NT" },
      { ref: "Isaiah 43:4", testament: "OT" },
      { ref: "Genesis 1:27", testament: "OT" },
      { ref: "Zephaniah 3:17", testament: "OT" },
      { ref: "Psalm 8:4–5", testament: "OT" },
      { ref: "Romans 5:8", testament: "NT" },
    ],
  },
  {
    slug: "spiritual-gifts",
    name: "Spiritual Gifts",
    description: "The Spirit distributes gifts as He wills — each believer is equipped to build up the body of Christ.",
    category: "Purpose & Identity",
    categorySlug: "purpose-identity",
    references: [
      { ref: "1 Corinthians 12:4–11", testament: "NT" },
      { ref: "Romans 12:6–8", testament: "NT" },
      { ref: "1 Peter 4:10–11", testament: "NT" },
      { ref: "Ephesians 4:7–16", testament: "NT" },
      { ref: "2 Timothy 1:6", testament: "NT" },
      { ref: "Matthew 25:14–30", testament: "NT" },
      { ref: "Proverbs 18:16", testament: "OT" },
      { ref: "1 Corinthians 14:1", testament: "NT" },
      { ref: "Hebrews 2:4", testament: "NT" },
      { ref: "1 Corinthians 12:28–31", testament: "NT" },
    ],
  },
  {
    slug: "vocation-work",
    name: "Vocation & Work",
    description: "Work was given before the Fall — whatever you do, do it as unto the Lord.",
    category: "Purpose & Identity",
    categorySlug: "purpose-identity",
    references: [
      { ref: "Genesis 2:15", testament: "OT" },
      { ref: "Colossians 3:23–24", testament: "NT" },
      { ref: "Ecclesiastes 3:22", testament: "OT" },
      { ref: "Proverbs 22:29", testament: "OT" },
      { ref: "2 Thessalonians 3:10", testament: "NT" },
      { ref: "1 Corinthians 10:31", testament: "NT" },
      { ref: "Ephesians 6:7–8", testament: "NT" },
      { ref: "Proverbs 12:11", testament: "OT" },
      { ref: "Ecclesiastes 9:10", testament: "OT" },
      { ref: "Matthew 25:21", testament: "NT" },
    ],
  },
  {
    slug: "stewardship",
    name: "Stewardship",
    description: "Everything belongs to God — we are managers, not owners, of what He has entrusted to us.",
    category: "Purpose & Identity",
    categorySlug: "purpose-identity",
    references: [
      { ref: "Luke 16:10–12", testament: "NT" },
      { ref: "1 Corinthians 4:2", testament: "NT" },
      { ref: "1 Peter 4:10", testament: "NT" },
      { ref: "Matthew 25:14–30", testament: "NT" },
      { ref: "Genesis 2:15", testament: "OT" },
      { ref: "Colossians 3:23", testament: "NT" },
      { ref: "Proverbs 27:23–24", testament: "OT" },
      { ref: "Psalm 24:1", testament: "OT" },
      { ref: "Luke 12:48", testament: "NT" },
      { ref: "Deuteronomy 8:17–18", testament: "OT" },
    ],
  },
  {
    slug: "missions-evangelism",
    name: "Missions & Evangelism",
    description: "Go into all the world — every believer is called to share the good news of Christ.",
    category: "Purpose & Identity",
    categorySlug: "purpose-identity",
    references: [
      { ref: "Matthew 28:19–20", testament: "NT" },
      { ref: "Mark 16:15", testament: "NT" },
      { ref: "Acts 1:8", testament: "NT" },
      { ref: "Romans 10:14–15", testament: "NT" },
      { ref: "1 Corinthians 9:22", testament: "NT" },
      { ref: "2 Corinthians 5:20", testament: "NT" },
      { ref: "Luke 24:47", testament: "NT" },
      { ref: "John 20:21", testament: "NT" },
      { ref: "Acts 17:30", testament: "NT" },
      { ref: "Proverbs 11:30", testament: "OT" },
    ],
  },
  {
    slug: "discipleship",
    name: "Discipleship",
    description: "Take up your cross and follow — discipleship is a lifelong journey of transformation.",
    category: "Purpose & Identity",
    categorySlug: "purpose-identity",
    references: [
      { ref: "Matthew 28:19–20", testament: "NT" },
      { ref: "Luke 9:23", testament: "NT" },
      { ref: "John 8:31–32", testament: "NT" },
      { ref: "Matthew 10:38", testament: "NT" },
      { ref: "Mark 8:34–35", testament: "NT" },
      { ref: "2 Timothy 2:2", testament: "NT" },
      { ref: "John 15:8", testament: "NT" },
      { ref: "Luke 14:27", testament: "NT" },
      { ref: "1 Corinthians 11:1", testament: "NT" },
      { ref: "2 Thessalonians 3:7–9", testament: "NT" },
    ],
  },

  // ── Life & Trials ─────────────────────────────────────────────────────────
  {
    slug: "suffering",
    name: "Suffering",
    description: "Present sufferings are not worth comparing to future glory — God redeems every trial.",
    category: "Life & Trials",
    categorySlug: "life-trials",
    references: [
      { ref: "Romans 8:18", testament: "NT" },
      { ref: "2 Corinthians 4:17", testament: "NT" },
      { ref: "James 1:2–4", testament: "NT" },
      { ref: "1 Peter 4:12–13", testament: "NT" },
      { ref: "Philippians 1:29", testament: "NT" },
      { ref: "Psalm 34:19", testament: "OT" },
      { ref: "John 16:33", testament: "NT" },
      { ref: "Romans 5:3–5", testament: "NT" },
      { ref: "Psalm 22:24", testament: "OT" },
      { ref: "2 Corinthians 12:9–10", testament: "NT" },
    ],
  },
  {
    slug: "trials-testing",
    name: "Trials & Testing",
    description: "The testing of your faith produces steadfastness — fire refines gold, and trials refine faith.",
    category: "Life & Trials",
    categorySlug: "life-trials",
    references: [
      { ref: "James 1:2–4", testament: "NT" },
      { ref: "1 Peter 1:6–7", testament: "NT" },
      { ref: "Romans 5:3–5", testament: "NT" },
      { ref: "Hebrews 12:7–11", testament: "NT" },
      { ref: "Job 23:10", testament: "OT" },
      { ref: "Psalm 66:10", testament: "OT" },
      { ref: "Proverbs 17:3", testament: "OT" },
      { ref: "Zechariah 13:9", testament: "OT" },
      { ref: "1 Corinthians 10:13", testament: "NT" },
      { ref: "Daniel 3:17–18", testament: "OT" },
    ],
  },
  {
    slug: "temptation",
    name: "Temptation",
    description: "God provides a way of escape — no temptation has overtaken you that is not common to man.",
    category: "Life & Trials",
    categorySlug: "life-trials",
    references: [
      { ref: "1 Corinthians 10:13", testament: "NT" },
      { ref: "James 1:12–15", testament: "NT" },
      { ref: "Matthew 6:13", testament: "NT" },
      { ref: "Hebrews 2:18", testament: "NT" },
      { ref: "Hebrews 4:15", testament: "NT" },
      { ref: "2 Peter 2:9", testament: "NT" },
      { ref: "Galatians 5:16", testament: "NT" },
      { ref: "Ephesians 6:10–18", testament: "NT" },
      { ref: "Matthew 4:1–11", testament: "NT" },
      { ref: "1 Peter 5:8–9", testament: "NT" },
    ],
  },
  {
    slug: "addiction-bondage",
    name: "Addiction & Bondage",
    description: "Whom the Son sets free is free indeed — Christ breaks every chain and restores the captive.",
    category: "Life & Trials",
    categorySlug: "life-trials",
    references: [
      { ref: "John 8:34–36", testament: "NT" },
      { ref: "2 Peter 2:19", testament: "NT" },
      { ref: "Galatians 5:1", testament: "NT" },
      { ref: "Romans 6:6–7", testament: "NT" },
      { ref: "1 Corinthians 6:12", testament: "NT" },
      { ref: "Proverbs 5:22", testament: "OT" },
      { ref: "Luke 4:18", testament: "NT" },
      { ref: "Isaiah 61:1", testament: "OT" },
      { ref: "John 8:36", testament: "NT" },
      { ref: "2 Corinthians 3:17", testament: "NT" },
    ],
  },
  {
    slug: "death-dying",
    name: "Death & Dying",
    description: "To live is Christ and to die is gain — death has lost its sting through the resurrection.",
    category: "Life & Trials",
    categorySlug: "life-trials",
    references: [
      { ref: "John 11:25–26", testament: "NT" },
      { ref: "Psalm 23:4", testament: "OT" },
      { ref: "Philippians 1:21", testament: "NT" },
      { ref: "2 Corinthians 5:1–8", testament: "NT" },
      { ref: "Revelation 14:13", testament: "NT" },
      { ref: "Psalm 116:15", testament: "OT" },
      { ref: "1 Corinthians 15:54–57", testament: "NT" },
      { ref: "Psalm 31:5", testament: "OT" },
      { ref: "Isaiah 25:8", testament: "OT" },
      { ref: "Hebrews 9:27", testament: "NT" },
    ],
  },
  {
    slug: "resurrection",
    name: "Resurrection",
    description: "Christ is risen — His resurrection guarantees the resurrection of all who are in Him.",
    category: "Life & Trials",
    categorySlug: "life-trials",
    references: [
      { ref: "1 Corinthians 15:20–23", testament: "NT" },
      { ref: "John 11:25", testament: "NT" },
      { ref: "Romans 6:4–5", testament: "NT" },
      { ref: "Philippians 3:10–11", testament: "NT" },
      { ref: "1 Thessalonians 4:14", testament: "NT" },
      { ref: "Acts 2:31–32", testament: "NT" },
      { ref: "2 Corinthians 4:14", testament: "NT" },
      { ref: "Revelation 20:5–6", testament: "NT" },
      { ref: "John 5:28–29", testament: "NT" },
      { ref: "Daniel 12:2", testament: "OT" },
    ],
  },
  {
    slug: "rest-sabbath",
    name: "Rest & Sabbath",
    description: "Come to Me, all who are weary — God built rest into creation and invites us into His rhythm.",
    category: "Life & Trials",
    categorySlug: "life-trials",
    references: [
      { ref: "Matthew 11:28–30", testament: "NT" },
      { ref: "Hebrews 4:9–11", testament: "NT" },
      { ref: "Exodus 20:8–11", testament: "OT" },
      { ref: "Mark 6:31", testament: "NT" },
      { ref: "Genesis 2:2–3", testament: "OT" },
      { ref: "Psalm 62:1", testament: "OT" },
      { ref: "Isaiah 30:15", testament: "OT" },
      { ref: "Psalm 116:7", testament: "OT" },
      { ref: "Isaiah 58:13–14", testament: "OT" },
      { ref: "Revelation 14:13", testament: "NT" },
    ],
  },
  {
    slug: "loss-disappointment",
    name: "Loss & Disappointment",
    description: "He restores what the locusts have eaten — God meets us in loss and works all things together.",
    category: "Life & Trials",
    categorySlug: "life-trials",
    references: [
      { ref: "Psalm 34:18", testament: "OT" },
      { ref: "Romans 8:28", testament: "NT" },
      { ref: "2 Corinthians 4:8–9", testament: "NT" },
      { ref: "Job 1:21", testament: "OT" },
      { ref: "Lamentations 3:22–23", testament: "OT" },
      { ref: "Psalm 30:5", testament: "OT" },
      { ref: "John 16:20", testament: "NT" },
      { ref: "Isaiah 61:3", testament: "OT" },
      { ref: "Psalm 46:1–3", testament: "OT" },
      { ref: "2 Corinthians 7:6", testament: "NT" },
    ],
  },
  {
    slug: "spiritual-warfare",
    name: "Spiritual Warfare",
    description: "Put on the full armor of God — our struggle is not against flesh and blood but against darkness.",
    category: "Life & Trials",
    categorySlug: "life-trials",
    references: [
      { ref: "Ephesians 6:10–18", testament: "NT" },
      { ref: "1 Peter 5:8–9", testament: "NT" },
      { ref: "2 Corinthians 10:3–5", testament: "NT" },
      { ref: "James 4:7", testament: "NT" },
      { ref: "Revelation 12:11", testament: "NT" },
      { ref: "1 John 4:4", testament: "NT" },
      { ref: "Matthew 4:1–11", testament: "NT" },
      { ref: "Luke 10:19", testament: "NT" },
      { ref: "Romans 8:37", testament: "NT" },
      { ref: "2 Corinthians 2:14", testament: "NT" },
    ],
  },
  {
    slug: "deliverance",
    name: "Deliverance",
    description: "The Lord rescues the righteous — He lifts the poor from the ash heap and sets captives free.",
    category: "Life & Trials",
    categorySlug: "life-trials",
    references: [
      { ref: "Luke 4:18", testament: "NT" },
      { ref: "Isaiah 61:1", testament: "OT" },
      { ref: "Psalm 34:4", testament: "OT" },
      { ref: "Psalm 107:13–14", testament: "OT" },
      { ref: "Galatians 5:1", testament: "NT" },
      { ref: "John 8:36", testament: "NT" },
      { ref: "Acts 10:38", testament: "NT" },
      { ref: "Colossians 1:13–14", testament: "NT" },
      { ref: "Psalm 40:1–3", testament: "OT" },
      { ref: "2 Samuel 22:2", testament: "OT" },
    ],
  },

  // ── Church & Community ────────────────────────────────────────────────────
  {
    slug: "the-church",
    name: "The Church",
    description: "Christ is the head, we are the body — the Church is God's plan to display His glory to the world.",
    category: "Church & Community",
    categorySlug: "church-community",
    references: [
      { ref: "Matthew 16:18", testament: "NT" },
      { ref: "Acts 2:42–47", testament: "NT" },
      { ref: "Ephesians 2:19–22", testament: "NT" },
      { ref: "Hebrews 10:24–25", testament: "NT" },
      { ref: "1 Corinthians 12:12–27", testament: "NT" },
      { ref: "Colossians 1:18", testament: "NT" },
      { ref: "Revelation 1:20", testament: "NT" },
      { ref: "1 Peter 2:9", testament: "NT" },
      { ref: "Ephesians 4:4–6", testament: "NT" },
      { ref: "Revelation 21:9", testament: "NT" },
    ],
  },
  {
    slug: "unity",
    name: "Unity & Division",
    description: "How good and pleasant when brothers dwell in unity — Christ prays that His people would be one.",
    category: "Church & Community",
    categorySlug: "church-community",
    references: [
      { ref: "John 17:20–23", testament: "NT" },
      { ref: "Philippians 2:1–2", testament: "NT" },
      { ref: "Ephesians 4:3–6", testament: "NT" },
      { ref: "1 Corinthians 1:10", testament: "NT" },
      { ref: "Romans 12:16", testament: "NT" },
      { ref: "Psalm 133:1–3", testament: "OT" },
      { ref: "Colossians 3:14", testament: "NT" },
      { ref: "Galatians 3:28", testament: "NT" },
      { ref: "Ephesians 4:13", testament: "NT" },
      { ref: "1 Peter 3:8", testament: "NT" },
    ],
  },
  {
    slug: "hospitality",
    name: "Hospitality",
    description: "Do not neglect to show hospitality to strangers — in serving others we serve the Lord.",
    category: "Church & Community",
    categorySlug: "church-community",
    references: [
      { ref: "Romans 12:13", testament: "NT" },
      { ref: "1 Peter 4:9", testament: "NT" },
      { ref: "Hebrews 13:2", testament: "NT" },
      { ref: "Luke 14:12–14", testament: "NT" },
      { ref: "Matthew 25:35", testament: "NT" },
      { ref: "Genesis 18:1–8", testament: "OT" },
      { ref: "3 John 1:5–8", testament: "NT" },
      { ref: "Titus 1:8", testament: "NT" },
      { ref: "Luke 10:38–42", testament: "NT" },
      { ref: "Isaiah 58:7", testament: "OT" },
    ],
  },
  {
    slug: "service",
    name: "Service & Servanthood",
    description: "The Son of Man came not to be served but to serve — greatness in God's kingdom is upside-down.",
    category: "Church & Community",
    categorySlug: "church-community",
    references: [
      { ref: "Mark 10:45", testament: "NT" },
      { ref: "Matthew 20:26–28", testament: "NT" },
      { ref: "John 13:12–17", testament: "NT" },
      { ref: "Galatians 5:13", testament: "NT" },
      { ref: "1 Peter 4:10–11", testament: "NT" },
      { ref: "Ephesians 4:12", testament: "NT" },
      { ref: "Colossians 3:23", testament: "NT" },
      { ref: "Acts 6:2–4", testament: "NT" },
      { ref: "Matthew 25:44–45", testament: "NT" },
      { ref: "Luke 22:27", testament: "NT" },
    ],
  },
  {
    slug: "leadership",
    name: "Leadership",
    description: "Shepherd the flock willingly — biblical leadership is sacrificial, humble, and Spirit-led.",
    category: "Church & Community",
    categorySlug: "church-community",
    references: [
      { ref: "1 Timothy 3:1–7", testament: "NT" },
      { ref: "Titus 1:5–9", testament: "NT" },
      { ref: "1 Peter 5:2–3", testament: "NT" },
      { ref: "Proverbs 11:14", testament: "OT" },
      { ref: "Mark 10:43–44", testament: "NT" },
      { ref: "Luke 22:26", testament: "NT" },
      { ref: "Joshua 1:9", testament: "OT" },
      { ref: "Nehemiah 2:18", testament: "OT" },
      { ref: "Ezekiel 34:2–4", testament: "OT" },
      { ref: "Hebrews 13:17", testament: "NT" },
    ],
  },
  {
    slug: "accountability",
    name: "Accountability",
    description: "Iron sharpens iron — bearing one another's burdens and speaking truth in love builds us up.",
    category: "Church & Community",
    categorySlug: "church-community",
    references: [
      { ref: "Galatians 6:1–2", testament: "NT" },
      { ref: "Hebrews 10:24–25", testament: "NT" },
      { ref: "Matthew 18:15–17", testament: "NT" },
      { ref: "Proverbs 27:17", testament: "OT" },
      { ref: "James 5:16", testament: "NT" },
      { ref: "Ecclesiastes 4:9–12", testament: "OT" },
      { ref: "1 Thessalonians 5:11", testament: "NT" },
      { ref: "Proverbs 15:22", testament: "OT" },
      { ref: "James 5:19–20", testament: "NT" },
      { ref: "2 Timothy 4:2", testament: "NT" },
    ],
  },
  {
    slug: "giving-tithing",
    name: "Giving & Tithing",
    description: "Bring the whole tithe into the storehouse — God honors the cheerful, faithful giver.",
    category: "Church & Community",
    categorySlug: "church-community",
    references: [
      { ref: "Malachi 3:10", testament: "OT" },
      { ref: "2 Corinthians 9:6–8", testament: "NT" },
      { ref: "Luke 21:1–4", testament: "NT" },
      { ref: "Proverbs 3:9–10", testament: "OT" },
      { ref: "Matthew 6:19–21", testament: "NT" },
      { ref: "Deuteronomy 14:22", testament: "OT" },
      { ref: "1 Corinthians 16:2", testament: "NT" },
      { ref: "Mark 12:41–44", testament: "NT" },
      { ref: "Luke 12:33–34", testament: "NT" },
      { ref: "Proverbs 11:24–25", testament: "OT" },
    ],
  },
  {
    slug: "spiritual-disciplines",
    name: "Spiritual Disciplines",
    description: "Train yourself for godliness — intentional practices that draw us deeper into God's presence.",
    category: "Church & Community",
    categorySlug: "church-community",
    references: [
      { ref: "1 Timothy 4:7–8", testament: "NT" },
      { ref: "Hebrews 12:11", testament: "NT" },
      { ref: "1 Corinthians 9:24–27", testament: "NT" },
      { ref: "Joshua 1:8", testament: "OT" },
      { ref: "Psalm 119:11", testament: "OT" },
      { ref: "Colossians 3:16", testament: "NT" },
      { ref: "Acts 2:42", testament: "NT" },
      { ref: "2 Timothy 3:16–17", testament: "NT" },
      { ref: "Psalm 1:1–3", testament: "OT" },
      { ref: "Luke 5:16", testament: "NT" },
    ],
  },

  // ── Society & Ethics ──────────────────────────────────────────────────────
  {
    slug: "justice",
    name: "Justice",
    description: "Let justice roll on like a river — God calls His people to champion the cause of the oppressed.",
    category: "Society & Ethics",
    categorySlug: "society-ethics",
    references: [
      { ref: "Micah 6:8", testament: "OT" },
      { ref: "Amos 5:24", testament: "OT" },
      { ref: "Isaiah 1:17", testament: "OT" },
      { ref: "Proverbs 21:15", testament: "OT" },
      { ref: "Psalm 82:3–4", testament: "OT" },
      { ref: "Deuteronomy 16:20", testament: "OT" },
      { ref: "Luke 18:1–8", testament: "NT" },
      { ref: "Matthew 23:23", testament: "NT" },
      { ref: "Isaiah 61:8", testament: "OT" },
      { ref: "Psalm 37:28", testament: "OT" },
    ],
  },
  {
    slug: "caring-for-the-poor",
    name: "Caring for the Poor",
    description: "Whoever is generous to the poor lends to the Lord — caring for the least reflects love for God.",
    category: "Society & Ethics",
    categorySlug: "society-ethics",
    references: [
      { ref: "Proverbs 19:17", testament: "OT" },
      { ref: "Matthew 25:35–40", testament: "NT" },
      { ref: "Luke 4:18", testament: "NT" },
      { ref: "Deuteronomy 15:7–11", testament: "OT" },
      { ref: "Proverbs 14:31", testament: "OT" },
      { ref: "Isaiah 58:6–7", testament: "OT" },
      { ref: "James 2:14–17", testament: "NT" },
      { ref: "Luke 14:13–14", testament: "NT" },
      { ref: "Proverbs 22:9", testament: "OT" },
      { ref: "Acts 2:44–45", testament: "NT" },
    ],
  },
  {
    slug: "creation-care",
    name: "Creation & Earth Care",
    description: "The earth is the Lord's — humanity is called to tend and keep what God has made.",
    category: "Society & Ethics",
    categorySlug: "society-ethics",
    references: [
      { ref: "Genesis 1:28", testament: "OT" },
      { ref: "Genesis 2:15", testament: "OT" },
      { ref: "Psalm 24:1", testament: "OT" },
      { ref: "Colossians 1:17", testament: "NT" },
      { ref: "Psalm 104:1–35", testament: "OT" },
      { ref: "Revelation 11:18", testament: "NT" },
      { ref: "Romans 8:19–22", testament: "NT" },
      { ref: "Proverbs 12:10", testament: "OT" },
      { ref: "Genesis 9:8–17", testament: "OT" },
      { ref: "Job 38:1–41", testament: "OT" },
    ],
  },
  {
    slug: "finances-money",
    name: "Finances & Money",
    description: "You cannot serve both God and money — Scripture gives profound wisdom on wealth and provision.",
    category: "Society & Ethics",
    categorySlug: "society-ethics",
    references: [
      { ref: "Matthew 6:24", testament: "NT" },
      { ref: "1 Timothy 6:10", testament: "NT" },
      { ref: "Proverbs 13:11", testament: "OT" },
      { ref: "Luke 16:10–13", testament: "NT" },
      { ref: "Hebrews 13:5", testament: "NT" },
      { ref: "Proverbs 22:7", testament: "OT" },
      { ref: "Matthew 25:14–30", testament: "NT" },
      { ref: "Luke 12:15–21", testament: "NT" },
      { ref: "Psalm 37:16", testament: "OT" },
      { ref: "Ecclesiastes 5:10", testament: "OT" },
    ],
  },
  {
    slug: "blessing-prosperity",
    name: "Blessing & Prosperity",
    description: "Blessed is the man who trusts in the Lord — God delights to bless those who walk in His ways.",
    category: "Society & Ethics",
    categorySlug: "society-ethics",
    references: [
      { ref: "Deuteronomy 28:1–14", testament: "OT" },
      { ref: "3 John 1:2", testament: "NT" },
      { ref: "Proverbs 10:22", testament: "OT" },
      { ref: "Psalm 1:1–3", testament: "OT" },
      { ref: "Jeremiah 29:11", testament: "OT" },
      { ref: "Genesis 12:2", testament: "OT" },
      { ref: "Ephesians 1:3", testament: "NT" },
      { ref: "Malachi 3:10–12", testament: "OT" },
      { ref: "Numbers 6:24–26", testament: "OT" },
      { ref: "Psalm 67:1–2", testament: "OT" },
    ],
  },
  {
    slug: "race-ethnicity",
    name: "Race & Ethnicity",
    description: "From every nation, tribe, and tongue — the diversity of humanity reflects the glory of God.",
    category: "Society & Ethics",
    categorySlug: "society-ethics",
    references: [
      { ref: "Galatians 3:28", testament: "NT" },
      { ref: "Revelation 7:9", testament: "NT" },
      { ref: "Acts 17:26", testament: "NT" },
      { ref: "Genesis 1:27", testament: "OT" },
      { ref: "Colossians 3:11", testament: "NT" },
      { ref: "John 4:1–42", testament: "NT" },
      { ref: "Acts 10:34–35", testament: "NT" },
      { ref: "Romans 10:12", testament: "NT" },
      { ref: "Luke 10:25–37", testament: "NT" },
      { ref: "Ephesians 2:14", testament: "NT" },
    ],
  },
  {
    slug: "the-law",
    name: "The Law & Torah",
    description: "The Law was our guardian until Christ — it reveals sin's depth and points us to the Savior.",
    category: "Society & Ethics",
    categorySlug: "society-ethics",
    references: [
      { ref: "Matthew 5:17–18", testament: "NT" },
      { ref: "Romans 3:20–22", testament: "NT" },
      { ref: "Galatians 3:24", testament: "NT" },
      { ref: "Psalm 119:97", testament: "OT" },
      { ref: "Deuteronomy 6:4–9", testament: "OT" },
      { ref: "Joshua 1:7–8", testament: "OT" },
      { ref: "Romans 7:7–12", testament: "NT" },
      { ref: "John 1:17", testament: "NT" },
      { ref: "Hebrews 8:6–13", testament: "NT" },
      { ref: "James 2:8–12", testament: "NT" },
    ],
  },
  {
    slug: "sacrifice",
    name: "Sacrifice",
    description: "Present your bodies as living sacrifices — from the altar of the OT to the cross, sacrifice points to God.",
    category: "Society & Ethics",
    categorySlug: "society-ethics",
    references: [
      { ref: "Hebrews 9:22", testament: "NT" },
      { ref: "Romans 12:1", testament: "NT" },
      { ref: "Psalm 51:17", testament: "OT" },
      { ref: "Hebrews 10:5–10", testament: "NT" },
      { ref: "Isaiah 53:10", testament: "OT" },
      { ref: "Leviticus 1:4", testament: "OT" },
      { ref: "1 Samuel 15:22", testament: "OT" },
      { ref: "1 Corinthians 5:7", testament: "NT" },
      { ref: "Hebrews 13:15–16", testament: "NT" },
      { ref: "Genesis 22:7–14", testament: "OT" },
    ],
  },
  {
    slug: "renewal-transformation",
    name: "Renewal & Transformation",
    description: "Be transformed by the renewing of your mind — God's Spirit makes all things new from the inside out.",
    category: "Society & Ethics",
    categorySlug: "society-ethics",
    references: [
      { ref: "Romans 12:2", testament: "NT" },
      { ref: "2 Corinthians 5:17", testament: "NT" },
      { ref: "Ephesians 4:22–24", testament: "NT" },
      { ref: "Titus 3:5", testament: "NT" },
      { ref: "Colossians 3:9–10", testament: "NT" },
      { ref: "Psalm 51:10", testament: "OT" },
      { ref: "Ezekiel 36:26", testament: "OT" },
      { ref: "John 3:3–8", testament: "NT" },
      { ref: "Isaiah 43:18–19", testament: "OT" },
      { ref: "2 Corinthians 4:16", testament: "NT" },
    ],
  },
  {
    slug: "the-holy-spirit",
    name: "The Holy Spirit",
    description: "The Spirit is our Counselor, Comforter, and Guide — He seals, fills, and empowers every believer.",
    category: "Society & Ethics",
    categorySlug: "society-ethics",
    references: [
      { ref: "John 14:26", testament: "NT" },
      { ref: "Acts 2:1–4", testament: "NT" },
      { ref: "John 16:13", testament: "NT" },
      { ref: "Galatians 5:22–23", testament: "NT" },
      { ref: "Romans 8:26–27", testament: "NT" },
      { ref: "1 Corinthians 12:13", testament: "NT" },
      { ref: "Ephesians 5:18", testament: "NT" },
      { ref: "Acts 1:8", testament: "NT" },
      { ref: "John 3:5–8", testament: "NT" },
      { ref: "Romans 8:14–16", testament: "NT" },
    ],
  },
  {
    slug: "heaven",
    name: "Heaven",
    description: "Eye has not seen nor ear heard — God has prepared a glorious eternal home for those who love Him.",
    category: "Society & Ethics",
    categorySlug: "society-ethics",
    references: [
      { ref: "John 14:1–4", testament: "NT" },
      { ref: "Revelation 21:1–4", testament: "NT" },
      { ref: "Philippians 3:20", testament: "NT" },
      { ref: "Hebrews 11:16", testament: "NT" },
      { ref: "Matthew 5:12", testament: "NT" },
      { ref: "2 Corinthians 5:1", testament: "NT" },
      { ref: "Revelation 22:1–5", testament: "NT" },
      { ref: "Luke 23:43", testament: "NT" },
      { ref: "1 Corinthians 15:49–54", testament: "NT" },
      { ref: "Psalm 16:11", testament: "OT" },
    ],
  },
  {
    slug: "second-coming",
    name: "Second Coming of Christ",
    description: "Christ will return in glory — every knee will bow, and His Kingdom will have no end.",
    category: "Society & Ethics",
    categorySlug: "society-ethics",
    references: [
      { ref: "Matthew 24:36–44", testament: "NT" },
      { ref: "1 Thessalonians 4:16–17", testament: "NT" },
      { ref: "Revelation 1:7", testament: "NT" },
      { ref: "Acts 1:11", testament: "NT" },
      { ref: "Revelation 22:12–20", testament: "NT" },
      { ref: "2 Peter 3:10", testament: "NT" },
      { ref: "Titus 2:13", testament: "NT" },
      { ref: "Matthew 25:13", testament: "NT" },
      { ref: "1 Corinthians 15:51–52", testament: "NT" },
      { ref: "Mark 13:32–33", testament: "NT" },
    ],
  },
  {
    slug: "aging",
    name: "Aging & Old Age",
    description: "Gray hair is a crown of glory — God honors the elderly and promises to sustain us even to old age.",
    category: "Society & Ethics",
    categorySlug: "society-ethics",
    references: [
      { ref: "Psalm 71:9", testament: "OT" },
      { ref: "Proverbs 16:31", testament: "OT" },
      { ref: "Titus 2:2–5", testament: "NT" },
      { ref: "Isaiah 46:4", testament: "OT" },
      { ref: "Psalm 92:12–14", testament: "OT" },
      { ref: "Genesis 25:8", testament: "OT" },
      { ref: "Ecclesiastes 12:1", testament: "OT" },
      { ref: "Leviticus 19:32", testament: "OT" },
      { ref: "Psalm 71:18", testament: "OT" },
      { ref: "Job 12:12", testament: "OT" },
    ],
  },
  {
    slug: "new-life-rebirth",
    name: "New Life & Rebirth",
    description: "You must be born again — God brings forth new life from death, making all things new.",
    category: "Society & Ethics",
    categorySlug: "society-ethics",
    references: [
      { ref: "John 3:3–8", testament: "NT" },
      { ref: "2 Corinthians 5:17", testament: "NT" },
      { ref: "1 Peter 1:23", testament: "NT" },
      { ref: "Titus 3:5", testament: "NT" },
      { ref: "Isaiah 43:18–19", testament: "OT" },
      { ref: "John 1:12–13", testament: "NT" },
      { ref: "Psalm 22:9–10", testament: "OT" },
      { ref: "Ecclesiastes 3:2", testament: "OT" },
      { ref: "Psalm 139:13–14", testament: "OT" },
      { ref: "Job 1:21", testament: "OT" },
    ],
  },
  {
    slug: "meditation-scripture",
    name: "Meditating on Scripture",
    description: "Blessed is the one who meditates on the law day and night — dwelling in God's Word transforms the mind.",
    category: "Society & Ethics",
    categorySlug: "society-ethics",
    references: [
      { ref: "Psalm 1:1–3", testament: "OT" },
      { ref: "Joshua 1:8", testament: "OT" },
      { ref: "Psalm 119:15", testament: "OT" },
      { ref: "Philippians 4:8", testament: "NT" },
      { ref: "Colossians 3:16", testament: "NT" },
      { ref: "Psalm 19:14", testament: "OT" },
      { ref: "Psalm 104:34", testament: "OT" },
      { ref: "Proverbs 4:20–22", testament: "OT" },
      { ref: "Psalm 119:97", testament: "OT" },
      { ref: "Joshua 1:7", testament: "OT" },
    ],
  },
];

export function getThemeBySlug(slug: string): BibleTheme | undefined {
  return BIBLE_THEMES.find((t) => t.slug === slug);
}

export function getThemesByCategory(categorySlug: string): BibleTheme[] {
  return BIBLE_THEMES.filter((t) => t.categorySlug === categorySlug);
}

export function getCategoryInfo(categorySlug: string) {
  return CATEGORIES.find((c) => c.slug === categorySlug);
}

export function searchThemes(query: string): BibleTheme[] {
  const q = query.toLowerCase();
  return BIBLE_THEMES.filter(
    (t) =>
      t.name.toLowerCase().includes(q) ||
      t.description.toLowerCase().includes(q) ||
      t.category.toLowerCase().includes(q)
  );
}
